# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userinfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='userinfo.proto',
  package='rpc_package',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0euserinfo.proto\x12\x0brpc_package\"\x1f\n\x0fUserInfoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"g\n\rUserInfoReply\x12\x0c\n\x04\x63ode\x18\x05 \x01(\x05\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06gender\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t2\\\n\x0fUserInfoService\x12I\n\x0bGetUserInfo\x12\x1c.rpc_package.UserInfoRequest\x1a\x1a.rpc_package.UserInfoReply\"\x00\x62\x06proto3'
)




_USERINFOREQUEST = _descriptor.Descriptor(
  name='UserInfoRequest',
  full_name='rpc_package.UserInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rpc_package.UserInfoRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=62,
)


_USERINFOREPLY = _descriptor.Descriptor(
  name='UserInfoReply',
  full_name='rpc_package.UserInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='rpc_package.UserInfoReply.code', index=0,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rpc_package.UserInfoReply.name', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='rpc_package.UserInfoReply.age', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='rpc_package.UserInfoReply.gender', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='rpc_package.UserInfoReply.date', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='rpc_package.UserInfoReply.message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['UserInfoRequest'] = _USERINFOREQUEST
DESCRIPTOR.message_types_by_name['UserInfoReply'] = _USERINFOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInfoRequest = _reflection.GeneratedProtocolMessageType('UserInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREQUEST,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.UserInfoRequest)
  })
_sym_db.RegisterMessage(UserInfoRequest)

UserInfoReply = _reflection.GeneratedProtocolMessageType('UserInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREPLY,
  '__module__' : 'userinfo_pb2'
  # @@protoc_insertion_point(class_scope:rpc_package.UserInfoReply)
  })
_sym_db.RegisterMessage(UserInfoReply)



_USERINFOSERVICE = _descriptor.ServiceDescriptor(
  name='UserInfoService',
  full_name='rpc_package.UserInfoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=169,
  serialized_end=261,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserInfo',
    full_name='rpc_package.UserInfoService.GetUserInfo',
    index=0,
    containing_service=None,
    input_type=_USERINFOREQUEST,
    output_type=_USERINFOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERINFOSERVICE)

DESCRIPTOR.services_by_name['UserInfoService'] = _USERINFOSERVICE

# @@protoc_insertion_point(module_scope)
