# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.grpc_demo.rpc_package import userinfo_pb2 as userinfo__pb2


class UserInfoServiceStub(object):
    """define a service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserInfo = channel.unary_unary(
                '/rpc_package.UserInfoService/GetUserInfo',
                request_serializer=userinfo__pb2.UserInfoRequest.SerializeToString,
                response_deserializer=userinfo__pb2.UserInfoReply.FromString,
                )


class UserInfoServiceServicer(object):
    """define a service
    """

    def GetUserInfo(self, request, context):
        """define the interface and data type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserInfo,
                    request_deserializer=userinfo__pb2.UserInfoRequest.FromString,
                    response_serializer=userinfo__pb2.UserInfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_package.UserInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserInfoService(object):
    """define a service
    """

    @staticmethod
    def GetUserInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc_package.UserInfoService/GetUserInfo',
            userinfo__pb2.UserInfoRequest.SerializeToString,
            userinfo__pb2.UserInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
